### ISSUE TITLE
你好，想要加你好友咨询一下libjpeg-turo如何去编译

### ISSUE THREAD

**Issue by githubzjh** [xiaoqiAndroid/Light#1]
libjpeg-turo 怎么去编译成android下可用的.so文件啊（ndk去编译c不是很了解啊），编译过程中需要处理那些东西啊，我的qq是767132387，卡在这里半天了，能否加我一下，请教您一下

**Comment by githubzjh** [comment]
或者说你帮我编译好，写一个使用的文档也行，多少钱我给你

**Comment by JavaNoober** [comment]
没事，我稍微告诉你你就懂了
