### ISSUE TITLE
您好，为什么我压缩本地图片会质量变大呢，我设置的是忽略图片宽高

### ISSUE THREAD

**Issue by TCTW** [xiaoqiAndroid/Light#4]

**Comment by JavaNoober** [comment]
你压缩的宽度高度是什么，把一个图片转换成bitmap，再转换成文件，这个过程如果不去处理，是会导致文件变大的。所以你最好把图片的宽度高度指定一下

**Comment by TCTW** [comment]
我宽高指定的是原文件宽高

**Comment by JavaNoober** [comment]
这个问题我是知道的，但是具体我也不太清楚，哪怕原生的也是一样的。网上查了一下，大致原因是图片文件转换成bitmap的时候，所占内存根据不同手机、不同分辨率是不同的，这时候bitmap再转换成与之前相同尺寸的图片反而会变大。建议你缩小尺寸，或者指定一下颜色模式

**Comment by TCTW** [comment]
好的我试试，非常感谢
