### ISSUE TITLE
参数混乱

### ISSUE THREAD

**Issue by zouchuqu** [xiaoqiAndroid/Light#5]
我发现一个bug,版本1.10。设置的宽和高不起作用（ignoreSize(false)），然后质量压缩参数的值变成变成图片的长边的参数，例子，我设置 quality（90），然后生成的图片的长边就变成90，quality（400），生成的图片长边就为400。

**Comment by zouchuqu** [comment]
我试了1.20版本没问题了

**Comment by JavaNoober** [comment]
早起版本有一点bug
