### ISSUE TITLE
透明图片压缩后变为黑色了

### ISSUE THREAD

**Issue by hunanqi** [xiaoqiAndroid/Light#6]

**Comment by JavaNoober** [comment]
颜色模式默认是565，565是没有透明度的所以会有这个问题，CompressArgs中你修改成Bitmap.Config.ARGB_8888试一下

**Comment by hunanqi** [comment]
@JavaNoober   我是设置的Bitmap.Config.ARGB_8888，经过查找资料，是因为我的图片是png，你压缩后使用的Bitmap.CompressFormat.JPEG格式的，我把我的图片在网上先转成jpeg 后 再压缩 就没有问题了。

**Comment by JavaNoober** [comment]
那应该就是这样，因为这个库是基于libjpeg，所以png的图片可能会有点问题
